api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Gelato/Cart/Entity'
            - '%kernel.project_dir%/src/Gelato/Order/Entity'
            - '%kernel.project_dir%/src/Gelato/Shipping/Entity'
            - '%kernel.project_dir%/src/Gelato/User/Entity'
